version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/frontend"
    minor-patch:
      update-types:
        - "patch"
        - "minor"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    minor-patch:
      update-types:
        - "patch"
        - "minor"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
