services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:80
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`nginx.dev.local`)
      traefik.http.services.nginx.loadbalancer.server.port: 80
      traefik.http.routers.nginx.middlewares: tinyauth

  tinyauth:
    container_name: tinyauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ADDRESS=0.0.0.0
      - SECRET=ghDaPuDFjvlBuF93zcacFrDiHFHTZhUh
      - ROOT_URL=http://dev.local
      - APP_URL=http://tinyauth.dev.local
      - USERS=user:$$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`tinyauth.dev.local`)
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
