name: Tinyauth CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: |
          cd site
          bun install

      - name: Build frontend
        run: |
          cd site
          bun run build

      - name: Copy frontend
        run: |
          cp -r site/dist internal/assets/dist

      - name: Run tests
        run: go test -v ./...
