name: Generate Sponsors List
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSORS_GENERATOR_PAT }}
          file: README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            docs: regenerate readme sponsors list
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: docs/update-readme
          title: |
            docs: regenerate readme sponsors list
          labels: bot
